name: jaap_latest
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_card_swiper: ^7.0.2
  audioplayers: ^6.1.0
  google_fonts: ^6.2.1
  http: ^1.2.2
  provider: ^6.1.2
  gif_control_csx: ^0.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
#    - assets/audio/audio.mp3
#    - assets/audio.mp3
  # - images/a_dot_ham.jpeg