name: jaap_latest
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_card_swiper: ^7.0.2
  audioplayers: ^6.1.0
  google_fonts: ^6.2.1
  http: ^1.2.2
  share_plus: ^10.0.0
  provider: ^6.1.2
  flutter_hooks: ^0.20.5
  shared_preferences: ^2.2.3
  audio_service: ^0.18.15
  #audio_service: ^0.18.15
  flutter_html: ^3.0.0-alpha.3
  #just_audio: ^0.9.39
  just_audio: ^0.9.42
  gif: ^2.3.0
  lottie: ^3.1.3
  flutter_gif: ^0.0.4
  confetti: ^0.8.0
  particles_flutter: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
#    - assets/audio/audio.mp3
#    - assets/audio.mp3
  # - images/a_dot_ham.jpeg